/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wtpmduserapi_java_api_CWtpMdApi */

#ifndef _Included_wtpmduserapi_java_api_CWtpMdApi
#define _Included_wtpmduserapi_java_api_CWtpMdApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    RegisterSpi
 * Signature: (Lwtpmduserapi_java_api/CWtpMdSpi;)V
 */
JNIEXPORT void JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_RegisterSpi
  (JNIEnv *, jobject, jobject);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    RegisterFront
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_RegisterFront
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqUserLogin
 * Signature: (Lwtpmduserapi_java_api/CWtpReqUserLoginField;)I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqUserLogin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqUserLogout
 * Signature: (Lwtpmduserapi_java_api/CWtpUserLogoutField;)I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqUserLogout
  (JNIEnv *, jobject, jobject);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqQrySymbol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqQrySymbol
  (JNIEnv *, jobject);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqQryQuotation
 * Signature: (Lwtpmduserapi_java_api/CWtpSymbolField;)I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqQryQuotation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqSubQuotation
 * Signature: ([Lwtpmduserapi_java_api/CWtpSymbolField;)I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqSubQuotation
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     wtpmduserapi_java_api_CWtpMdApi
 * Method:    ReqUnSubQuotation
 * Signature: ([Lwtpmduserapi_java_api/CWtpSymbolField;)I
 */
JNIEXPORT jint JNICALL Java_wtpmduserapi_1java_1api_CWtpMdApi_ReqUnSubQuotation
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
